version: '3.8'

services:
  web:
    build: .
    working_dir: /app/src
    ports:
      - "8060:8060"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 