name: Deployment Mainbranch

## START MAIN PUSH
on:
  push:
    branches:
      - main
jobs:
  dockerBuildPush:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          # registry: docker.io
          push: true
          tags: buchingerwilhelmi/databank-dash:latest,buchingerwilhelmi/databank-dash:${{ github.run_number }}
          file: Dockerfile

  update-cluster-config:
    needs: dockerBuildPush
    runs-on: ubuntu-latest
    steps:
      - name: Push to Cluster Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CHECKOUTTOKEN }}
          RUN_NUMBER: ${{ github.sha }}
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/BuchingerWilhelmiApp/BWClusterConfig

          cd BWClusterConfig
          git config user.name "GithubAction"
          git config user.email "dev@bw.com"

          git checkout stackIT
          
          cd cluster/databank-dash/
          sed -i "s#tag: [0-9]\\+#tag: ${{ github.run_number }}#" values.yaml
          git status
          git add .
          git commit -m "databank-dash version upgraded"
          git status

          # git remote -v # Prints:
          # origin ***github.com/owner/my-repo.git (fetch)
          # origin ***github.com/owner/my-repo.git (push)

          git push origin stackIT # This does not work
## END MAIN PUSH
